### ISSUE TITLE
Building failed in mingw64 on windows 10

### ISSUE THREAD

**Issue by wangyixiang** [tanluteam/libmidi#1]
## error log | 日志或报错信息 

D:/sources/tanlu/libmidi/libmidi/playmidi.c: At top level:
cc1.exe: note: unrecognized command-line option '-Wno-writable-strings' may have been intended to silence earlier diagnostics
cc1.exe: note: unrecognized command-line option '-Wno-writable-strings' may have been intended to silence earlier diagnostics
[30/97] Building C object libmidi/CMakeFiles/midi.dir/quantity.c.obj
[31/97] Building C object libmidi/CMakeFiles/midi.dir/mt19937ar.c.obj
[32/97] Building C object CMakeFiles/sample.dir/test/sample.c.obj
[33/97] Building C object libmidi/CMakeFiles/midi.dir/url_pipe.c.obj
[34/97] Building C object CMakeFiles/timidity.dir/test/timidity.c.obj
[35/97] Building C object libmidi/CMakeFiles/midi.dir/url_dir.c.obj
[36/97] Building C object libmidi/CMakeFiles/midi.dir/sbkconv.c.obj
[37/97] Building C object libmidi/CMakeFiles/midi.dir/url_mem.c.obj
[38/97] Building C object libmidi/CMakeFiles/midi.dir/ncurs_c.c.obj
FAILED: libmidi/CMakeFiles/midi.dir/ncurs_c.c.obj
D:\msys64\mingw64\bin\cc.exe -DNO_MIDI_CACHE=1 -Dmidi_EXPORTS -ID:/sources/tanlu/libmidi/libmidi -ID:/msys64/mingw64/include/SDL2 -Wno-deprecated-declarations -Wno-writable-strings -Wno-deprecated-declarations -Wno-writable-strings -MD -MT libmidi/CMakeFiles/midi.dir/ncurs_c.c.obj -MF libmidi\CMakeFiles\midi.dir\ncurs_c.c.obj.d -o libmidi/CMakeFiles/midi.dir/ncurs_c.c.obj -c D:/sources/tanlu/libmidi/libmidi/ncurs_c.c
D:/sources/tanlu/libmidi/libmidi/ncurs_c.c:8:10: fatal error: ncurses.h: No such file or directory
    8 | #include <ncurses.h>
      |          ^~~~~~~~~~~
compilation terminated.

## context | 编译/运行环境

gcc.exe (Rev5, Built by MSYS2 project) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

cmake version 3.21.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

## how to reproduce | 复现步骤
1.clone the code
2.make build directory
3. cd build; cmake ..; cmake --build . --config Release

**Comment by DickyQi** [comment]
if you are using msys64/mingw64 please install ncurses-devel from msys use following command in msys64 shell
$pacman -Sy ncurses-devel

After finished install, reconfigure your project and re-build.
